spin_manifest_version = 2

[application]
name = "rusthttp"
version = "0.1.0"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "rusthttp"

[component.rusthttp]
source = "target/wasm32-wasip1/release/rusthttp.wasm"
allowed_outbound_hosts = []
[component.rusthttp.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
