name: Deploy Rust http
on:
  push:
    branches:
      - main
      - variables
    tags:
      - "v*"

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ github.token }}
          plugins: cloud

      # - name: Install latest Rust stable toolchain
      #   shell: bash
      #   run: |
      #     rustup toolchain install 1.73 --component clippy --component rustfmt
      #     rustup default 1.73

      # - name: "Install Wasm Rust target"
      #   run: rustup target add wasm32-wasi && rustup target add wasm32-unknown-unknown
      #   shell: bash

      # - uses: Swatinem/rust-cache@v2
      #   with:
      #     shared-key: "${{ runner.os }}-full-${{ hashFiles('./streaming-api/Cargo.lock') }}"

      - name: build and deploy
        uses: fermyon/actions/spin/deploy@v1
        id: deploy
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
          manifest_file: spin.toml
          run_build: false
