name: Deploy Rust http
on:
  push:
    branches:
      - main
      - variables
    tags:
      - "v*"

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest Rust stable toolchain
        shell: bash
        run: |
          rustup toolchain install 1.86 --component clippy --component rustfmt
          rustup default 1.86

      - name: "Install Wasm Rust target"
        run: rustup target add wasm32-wasip1 && rustup target add wasm32-unknown-unknown
        shell: bash

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-full-${{ hashFiles('./Cargo.lock') }}"

      - name: setup spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ github.token }}
          plugins: aka

      - name: build app
        run: spin build

      - name: build and deploy
        uses: rajatjindal/actions/spin/aka-deploy@also-known-as
        id: deploy
        with:
          fermyon_aka_token: ${{ secrets.FERMYON_AKA_TOKEN }}
          manifest_file: spin.toml
          run_build: false
          account_id: "79692a99-5c7f-4e32-b4db-eaf3fa0379a2"

