name: Deploy Rust http
on:
  push:
    branches:
      - main
      - variables
    tags:
      - "v*"

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ github.token }}
          plugins: cloud,aka

      - name: build and deploy
        uses: rajatjindal/actions/spin/aka-deploy@also-known-as
        id: deploy
        with:
          fermyon_aka_token: ${{ secrets.FERMYON_AKA_TOKEN }}
          manifest_file: spin.toml
          run_build: false
