name: deploy app preview
on:
  pull_request:
    branches: "main"
    types: ['opened', 'synchronize', 'reopened', 'closed']

permissions:
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork }}
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4

      - name: Install latest Rust stable toolchain
        shell: bash
        run: |
          rustup toolchain install 1.86 --component clippy --component rustfmt
          rustup default 1.86

      - name: "Install Wasm Rust target"
        run: rustup target add wasm32-wasip1 && rustup target add wasm32-unknown-unknown
        shell: bash

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-full-${{ hashFiles('./Cargo.lock') }}"

      - name: Setup `spin`
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          plugins: aka

      - name: build and deploy preview
        uses: rajatjindal/actions/spin/aka-preview@also-known-as
        with:
          fermyon_aka_token: ${{ secrets.FERMYON_AKA_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          undeploy: ${{ github.event.pull_request && github.event.action == 'closed' }}
          account_id: "79692a99-5c7f-4e32-b4db-eaf3fa0379a2"
